---
- name: Check if CLI script already exists in Build directory
  stat:
    path: '{{ DEST_PATH }}/{{ BUILD_DIR }}/config/cli-script'
  register: cli_result

- name: Remove existing module
  file:
    path: '{{ DEST_PATH }}/{{ BUILD_DIR }}/config/cli-script'
    state: absent
  when: cli_result.stat.exists

- name: A Jinja2 template to create EAP CLI 
  template:
    src: eap_cli_template.j2
    dest: '{{ DEST_PATH }}/{{ BUILD_DIR }}/config/cli-script'
