---
- hosts: localhost
  gather_facts: false

  vars:
    nsnm: 'default'
    #image_name: 'abin23abraham/mytestregistry'
    #image_tag: 'eap-test'
    local_registry_url: 'localhost:5000'
    image_name: 'eap72-test'
    image_tag: 'latest'
    replicas: 2
    app_name: 'eap72'
    cm_name: 'eap72-java-opts'
    cm_key: 'java_opts'
    resource_mem_request: '750Mi'
    resource_mem_limit: '1000Mi'
    ingress_host: 'eap72-test.info'
    createResources: true
    deleteResources: false
    deployment: true
    service: true
    ingress: true

  roles:
    - role: k8sCreate
      tags: k8sCreateObjects
      when: createResources

    - role: k8sDelete
      tags: k8sDeleteObjects
      when: deleteResources