---
- name: Check if service object found 
  command: kubectl get svc {{ app_name }} -n {{ nsnm }} -o name
  register: deployment_name
  changed_when: false
  ignore_errors: true
# Otherwise will start minikube
- name: Delete the service object if found.
  command: kubectl delete svc {{ app_name }} -n {{ nsnm }}
  when: 'deployment_name.stdout'
