---
- name: Delete the deployment object
  import_tasks: deleteDeployment.yml
  when: deployment

- name: Delete the service object
  import_tasks: deleteService.yml
  when: service

- name: Delete the ingress object
  import_tasks: deleteIngress.yml
  when: ingress

