---   
- name: Build an image and push it to a local repo
  docker_image:
    build:
      path: "{{ DEST_PATH }}/{{ BUILD_DIR }}"
      pull: false
      nocache: yes
    name: "{{ LOCAL_REGISTRY_URL }}/{{ IMAGE_NAME }}"
    tag: "{{ IMAGE_TAG }}"
    push: yes
    source: build