---
- name: Create a Deployment for EAP 72.
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app_name }}"
        namespace: "{{ nsnm }}"
      spec:
        replicas: "{{ replicas }}"
        selector:
          matchLabels:
            app: "{{ app_name }}"
        template:
          metadata:
            labels:
              app: "{{ app_name }}"
          spec:
            containers:
              - name: "{{ app_name }}"
                #image: "{{ image_name }}:{{ image_tag }}"
                image: "{{ local_registry_url }}/{{ image_name }}"
                imagePullPolicy: Always
                env:
                  - name: JAVA_OPTS
                    valueFrom:
                      configMapKeyRef:
                        name: "{{ cm_name }}"
                        key: "{{ cm_key }}"
                resources:
                  requests:
                    memory: "{{ resource_mem_request }}"
                  limits:
                    memory: "{{ resource_mem_limit }}"
                ports:
                  - containerPort: 8080
                
