---
- name: Get source code from Github
  import_tasks: getSourceCode.yml

- name: Get EAP package from Repository
  import_tasks: getEAPPackage.yml

- name: Get EAP Patch artifact from Repository
  import_tasks: getEAPPatch.yml

- name: Get APP artifact from Repository
  import_tasks: getAppArtifact.yml

- name: Get Module from Repository
  import_tasks: getModules.yml
