---
- name: Create a ConfigMap for Kubernetes.
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ cm_name }}"
        namespace: "{{ nsnm }}"
      data:
        java_opts: "{{ java_opts }}"
